apiVersion: v2
name: rudderstack
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

# WIP
#dependencies: 
#  - name: nginx-ingress
#    version: ~1.6.0
#    repository: https://helm.nginx.com/stable
#    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#    tags: # (optional)
#      - Tags can be used to group charts for enabling/disabling together
#    enabled: (optional) Enabled bool determines if chart should be loaded
#    import-values: # (optional)
#      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
#    alias: (optional) Alias usable alias to be used for the chart. Useful when you have to add the same chart multiple times
