---
{{- $baseConfig := .Files.Get "rudder-config.yaml" | fromYaml -}}
{{- $mergedConfig := mustMergeOverwrite $baseConfig .Values.backend.config.overrides -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    app: {{ include "backend.name" . }}
    release: {{ .Release.Name | quote }}
    {{- include "rudderstack.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ $mergedConfig | toYaml | nindent 4 }}
  google-application-credentials.json: |-
{{.Files.Get "rudder-google-application-credentials.json" | indent 4}}
  {{- if .Values.backend.controlPlaneJSON}}
  workspaceConfig.json: |-
{{.Files.Get "workspaceConfig.json" | indent 4}}
  {{- end }}
