{{- if .Values.telegraf_sidecar.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf-sidecar.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "telegraf-sidecar.name" . }}
    helm.sh/chart: {{ include "telegraf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  telegraf.conf: |+
    [global_tags]
    namespace = "${KUBE_NAMESPACE}"
    [agent]
    collection_jitter = "0s"
    debug = false
    flush_interval = "10s"
    flush_jitter = "0s"
    hostname = "$HOSTNAME"
    interval = {{quote .Values.telegraf_sidecar.config.agent.interval}}
    logfile = ""
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    omit_hostname = false
    precision = ""
    quiet = false
    round_interval = true
    [[processors.enum]]
    [[processors.enum.mapping]]
    dest = "status_code"
    field = "status"
    [processors.enum.mapping.value_mappings]
    critical = 3
    healthy = 1
    problem = 2
    {{template "telegraf-sidecar.outputs" .Values.telegraf_sidecar.config.outputs}}
    [[inputs.statsd]]
    allowed_pending_messages = 10000
    metric_separator = "_"
    percentile_limit = 100
    percentiles = [
        {{- $numOut := len .Values.telegraf_sidecar.config.statsd_percentiles }}
        {{- $numOut = sub $numOut 1 }}
        {{- range $b, $val := .Values.telegraf_sidecar.config.statsd_percentiles }}
        {{- $i := int64 $b }}
        {{- if eq $i $numOut }}
        {{ $val  }}
        {{- else }}
        {{ $val }},
        {{- end }}
        {{- end }}
        ]
    service_address = ":8125"


{{- end}}
