{{- if not .Values.rudderWorkspaceTokenExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rudderstack.rudderWorkspaceTokenSecretName" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
type: Opaque
data:
   rudderWorkspaceToken: {{ required "value for either .Values.rudderWorkspaceTokenExistingSecret or .Values.rudderWorkspaceToken is expected" .Values.rudderWorkspaceToken | b64enc | quote }}
{{- end }}

