{{- if .Values.telegraf_sidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rudderstack.fullname" . }}-telegraf-config
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
data:
  telegraf.conf: |+
    [global_tags]
    namespace = "${KUBE_NAMESPACE}"
    [agent]
    collection_jitter = "0s"
    debug = false
    flush_interval = "10s"
    flush_jitter = "0s"
    hostname = "$HOSTNAME"
    interval = {{ quote .Values.telegraf_sidecar.config.agent.interval }}
    logfile = ""
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    omit_hostname = false
    precision = ""
    quiet = false
    round_interval = true
    [[processors.enum]]
    [[processors.enum.mapping]]
    dest = "status_code"
    field = "status"
    [processors.enum.mapping.value_mappings]
    critical = 3
    healthy = 1
    problem = 2
    {{template "telegraf-sidecar.outputs" .Values.telegraf_sidecar.config.outputs}}
    [[inputs.statsd]]
    allowed_pending_messages = 10000
    metric_separator = "_"
    percentile_limit = 100
    percentiles = [ {{- .Values.telegraf_sidecar.config.statsd_percentiles | join ", " -}} ]
    service_address = ":8125"
{{- end }}
