{{- if .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rudderstack.rudderWorkspaceTokenSecretName" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value :=  .Values.vault.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: Opaque
data:
   rudderWorkspaceToken: {{ .Values.vault.rudderWorkspaceToken | b64enc | quote }}
{{- end }}
