{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
{{- end }}