apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rudderstack.fullname" . }}-jobs
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_POD_NAME: {{ include "rudderstack.fullname" . }}-postgresql
  POSTGRES_HEADLESS_SVC: {{ include "rudderstack.fullname" . }}-postgresql-hl
  JOBS_DB_HOST: "This is expected to be set by docker entrypoint script"
  {{- with .Values.postgresql }}
  JOBS_DB_PORT: {{ .primary.service.port | quote }}
  JOBS_DB_USER: {{ .auth.username | quote }}
  JOBS_DB_DB_NAME: {{ .auth.database | quote }}
  JOBS_DB_PASSWORD: {{ .auth.password | quote }}
  {{- end }}
