apiVersion: {{ include "statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "rudderstack.fullname" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rudderstack.fullname" . }}
  replicas: {{ .Values.global.backendReplicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "rudderstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rudderstack.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/rudder-config: {{ .Files.Get "rudder-config.yaml" | sha256sum }}
        checksum/rudder-bigquery-credentials: {{ .Files.Get "bigquery-credentials.json" | sha256sum }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ default "default" .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.backend.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.backend.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.backend.configMapName }}
        - configMap:
            defaultMode: 420
            name: {{ .Values.backend.configMapName }}
          name: backend-config-volume
        {{- end }}
        - configMap:
            defaultMode: 0777
            name: {{ include "backend.fullname" . }}-scripts
          name: backend-scripts-volume
        {{- if .Values.telegraf_sidecar.enabled }}
        - name: telegraf
          configMap:
            defaultMode: 420
            name: {{ include "telegraf-sidecar.fullname" . }}-config
        {{- end }}
        {{- if .Values.gcpCredentialSecret.enabled }}
        - name: google-application-credentials
          secret:
            defaultMode: 420
            secretName: {{ include "rudderstack.fullname" . }}-gcp
        {{- end }}
        {{- if eq .Values.postgresql.mode "sidecar" }}
        - name: {{ include "backend.name" . }}-postgresql-data
          emptyDir: {}
        {{- end }}
      containers:
      - name: {{ include "backend.name" . }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.version }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ .Values.backend.config.mountPath }}
          name: backend-config-volume
        - mountPath: {{ .Values.backend.scripts.mountPath }}
          name: backend-scripts-volume
        - mountPath: {{ .Values.backend.persistence.mountPath }}
          name: {{ include "backend.name" . }}-data
        {{- if .Values.gcpCredentialSecret.enabled }}
        - mountPath: {{ .Values.gcpCredentialSecret.mountPath }}
          name: google-application-credentials
        {{- end }}
        ports:
          - name: backend
            containerPort: {{ .Values.backend.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.targetPort }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        env:
          {{- if .Values.backend.extraEnvVars }}
            {{- .Values.backend.extraEnvVars | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.rudderWorkspaceToken }}
          - name: CONFIG_BACKEND_TOKEN
            value: {{ .Values.rudderWorkspaceToken }}
          {{- end }}
          {{- if .Values.backend.controlPlaneJSON }}
          - name: RSERVER_BACKEND_CONFIG_CONFIG_FROM_FILE
            value: "{{ .Values.backend.controlPlaneJSON }}"
          - name:  RSERVER_BACKEND_CONFIG_CONFIG_JSONPATH
            value: "{{ .Values.backend.config.mountPath }}/workspaceConfig.json"
          {{- end}}
          - name: COMPUTE_DB_HOST_IN_K8S
            value: {{ include "postgresql.computeDBHost" . }}
          - name: DEST_TRANSFORM_URL
            value: "http://{{ include "transformer.fullname" . }}:{{ .Values.transformer.service.port}}"
          - name: JOBS_DB_HOST
            value: "{{ .Values.postgresql.host }}"
          - name: JOBS_DB_USER
            value: "{{ .Values.postgresql.username }}"
          - name: JOBS_DB_PORT
            value: "{{ .Values.postgresql.port }}"
          - name: JOBS_DB_DB_NAME
            value: "{{ .Values.postgresql.database }}"
          - name: JOBS_DB_PASSWORD
            value: "{{ .Values.postgresql.password }}"
          - name: INSTANCE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBE_NAMESPACE
            value: {{ .Release.Namespace }}
        command: ["/docker-entrypoint.sh"]
        args: ["/bin/sh","-c","/wait-for $JOBS_DB_HOST:$(JOBS_DB_PORT) -- /rudder-server"]
        {{- if .Values.backend.controlPlaneJSON }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "{{ .Values.backend.scripts.mountPath }}/pre-stop.sh > /proc/1/fd/1"]
        {{- end }}
      {{- if .Values.telegraf_sidecar.enabled }}
      - name: {{ include "telegraf-sidecar.name" .}}
        image: "{{ .Values.telegraf_sidecar.image.repo }}:{{ .Values.telegraf_sidecar.image.tag }}"
        imagePullPolicy: {{ default "" .Values.telegraf_sidecar.image.pullPolicy | quote }}
        env:
          - name: KUBE_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: ENV
            value: {{ .Values.global.env }}
          {{- if .Values.telegraf_sidecar.extraEnvVars }}
            {{- .Values.telegraf_sidecar.extraEnvVars | toYaml | nindent 10 }}
          {{- end }}
        command: ["telegraf"]
        args: ["--config", "{{.Values.telegraf_sidecar.config.mountPath}}/telegraf.conf"]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep {{ .Values.backend.lifecycleSleepTime }}"]
        {{- if .Values.telegraf_sidecar.resources }}
        resources:
        {{- toYaml .Values.telegraf_sidecar.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: telegraf
            mountPath: {{.Values.telegraf_sidecar.config.mountPath}}
      {{- end }}
      {{- if eq .Values.postgresql.mode "sidecar" }}
      - name: {{ include "postgresql.name" .}}
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ default "" .Values.postgresql.image.pullPolicy | quote }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        volumeMounts:
          - name: {{ include "backend.name" . }}-postgresql-data
            mountPath: {{ .Values.postgresql.persistence.mountPath }}
        ports:
          - name: postgresql
            containerPort: {{ template "postgresql.port" . }}
        env:
          {{- if .Values.postgresql.extraEnvVars }}
            {{- .Values.postgresql.extraEnvVars | toYaml | nindent 10 }}
          {{- end }}
          - name: PGDATA
            value: "{{ .Values.postgresql.persistence.mountPath }}/pgdata"
          - name: POSTGRES_DB
            value: "{{ .Values.postgresql.database }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgresql.username }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgresql.password }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U {{ include "postgresql.username" . | quote }} -d {{ (include "postgresql.database" .) | quote }} -h 127.0.0.1 -p {{ template "postgresql.port" . }}
          initialDelaySeconds: {{ .Values.postgresql.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgresql.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgresql.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.postgresql.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.postgresql.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U {{ include "postgresql.username" . | quote }} -d {{ (include "postgresql.database" .) | quote }} -h 127.0.0.1 -p {{ template "postgresql.port" . }}
          initialDelaySeconds: {{ .Values.postgresql.readinessProbe.initialDelaySeconds }}
          periodSeconds:  {{ .Values.postgresql.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgresql.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.postgresql.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.postgresql.readinessProbe.failureThreshold }}
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "sleep {{ .Values.backend.lifecycleSleepTime }}" ]
      {{ end }}

  volumeClaimTemplates:
    - metadata:
        name: {{ include "backend.name" . }}-data
    {{- with .Values.backend.persistence.annotations }}
      annotations:
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
      spec:
        storageClassName: {{ .Values.global.storageClass }}
        accessModes:
        {{- range .Values.backend.persistence.accessModes }}
         - {{ . | quote }}
        {{- end }}
        resources:
          requests:
           storage: {{ .Values.backend.persistence.size | quote }}
