{{- if .Values.gcpCredentialSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rudderstack.fullname" . }}-gcp
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  google-application-credentials.json: {{ .Values.gcpCredentialSecret.jsonKeyFile | quote }}
{{- end }}
