apiVersion: v1
kind: Service
metadata:
  name: {{ include "rudderstack.fullname" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
    {{- with .Values.backend.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.backend.service }}
    {{- with .labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: http
{{- end }}
  selector:
    {{- include "rudderstack.backend.selectorLabels" . | nindent 4 }}
